apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-pvc-benchmark
spec:
  completions: 4
  # starting 4 pods in parallel while using the standard testcase results in
  # 16 threads reading and writing to 4 PVs; 8x random reads, 4x randowm writes
  # and 4x random readwrites
  parallelism: 4
  template:
    spec:
      volumes:
      - name: fio-data-volume
        persistentVolumeClaim:
          claimName: benchmark-pvc
      containers:
      - name: fio
        image: quay.io/loodsemanuel/k8s-pvc-benchmark:master
        env:
        - name: FIO_TEST_PATH
          value: "/fio-data"
        - name: FIO_CONF_FILE
          value: "/config.fio"
        volumeMounts:
        - mountPath: "/fio-data"
          name: fio-data-volume
      restartPolicy: Never
  backoffLimit: 4